apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: play-ingress
  namespace: play
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          # authentication-svc → /auth/...
          - path: /auth(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: authentication-svc
                port:
                  number: 8001

          # trails-activities-svc → /trails/...
          - path: /trails(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: trails-activities-svc
                port:
                  number: 8002

          # points-vouchers-rules-svc → /points/...
          - path: /points(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: points-vouchers-rules-svc
                port:
                  number: 8003

          # qr-checkin-svc → /qr/...
          - path: /qr(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: qr-checkin-svc
                port:
                  number: 8004

          # leaderboard-attendance-svc → /leaderboard/...
          - path: /leaderboard(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: leaderboard-attendance-svc
                port:
                  number: 8005
