"""add organiser credentials

Revision ID: 6fe2c85d7514
Revises: 
Create Date: 2025-11-02 21:19:36.076047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fe2c85d7514'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if 'credentials' not in inspector.get_table_names():
        raise RuntimeError(
            "Table 'credentials' does not exist. "
            "Ensure the baseline schema is created before running this migration."
        )

    existing_columns = {column["name"] for column in inspector.get_columns('credentials')}
    if 'admin_username' not in existing_columns:
        op.add_column('credentials', sa.Column('admin_username', sa.String(length=255), nullable=True))

    if 'admin_password_hash' not in existing_columns:
        op.add_column('credentials', sa.Column('admin_password_hash', sa.String(length=255), nullable=True))

    existing_unique_constraints = {
        constraint["name"] for constraint in inspector.get_unique_constraints('credentials')
    }
    if 'uq_credentials_admin_username' not in existing_unique_constraints:
        op.create_unique_constraint('uq_credentials_admin_username', 'credentials', ['admin_username'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_credentials_admin_username', 'credentials', type_='unique')
    op.drop_column('credentials', 'admin_password_hash')
    op.drop_column('credentials', 'admin_username')
    # ### end Alembic commands ###
