"""add organiser credentials

Revision ID: 6fe2c85d7514
Revises: 
Create Date: 2025-11-02 21:19:36.076047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fe2c85d7514'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credentials', sa.Column('admin_username', sa.String(length=255), nullable=True))
    op.add_column('credentials', sa.Column('admin_password_hash', sa.String(length=255), nullable=True))
    op.create_unique_constraint('uq_credentials_admin_username', 'credentials', ['admin_username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_credentials_admin_username', 'credentials', type_='unique')
    op.drop_column('credentials', 'admin_password_hash')
    op.drop_column('credentials', 'admin_username')
    # ### end Alembic commands ###
